name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v4
      with:
        resource-group: rg_Ali_Alsuleyman
        cluster-name: aks-zerohero

    - run: kubectl apply -f deployment.yaml
